package com.utility.utility_billing_system.entity;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Abstract base class for all JPA entities providing primary key and audit timestamps.
 * <p>
 * {@code @PrePersist} and {@code @PreUpdate} hooks automatically set createdAt/updatedAt.
 */
@Getter
@Setter
@MappedSuperclass
public abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    /** Surrogate primary key auto-generated by the database. */
    private Long id;

    @Column(name = "created_at", nullable = false, updatable = false)
    /** Timestamp when the record was first persisted. */
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    /** Timestamp of the most recent update. */
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
